### ISSUE TITLE
pushplus不推送

### ISSUE THREAD

**Issue by noshore** [RayWangQvQ/BiliBiliToolPro#45]
（提issue前请先确认没有其他人提过相同的议题）
github action部署云函数 除了secret需要添加一个PUSHPLUSTOKEN之外 还需要配置什么吗 
添加了secret之后没有推送
云函数日志显示：
[11:54:47 INF] ·开始推送·Daily任务·

[11:54:47 INF] 运行结束

函数结束

=>返回 {"key1":"test value 1","key2":"test value 2"}

=>推送函数处理结果

Response RequestId: 5fbcc9d1-f0a7-4208-a3f2-a286abc592bc RetMsg: {"key1":"test value 1","key2":"test value 2"}

END RequestId: 5fbcc9d1-f0a7-4208-a3f2-a286abc592bc

Report RequestId: 5fbcc9d1-f0a7-4208-a3f2-a286abc592bc Duration: 904442ms Memory: 128MB MemUsage: 43.80MB

**Comment by noshore** [comment]
已解决
github action添加secret好像有问题 并不会自动转成环境变量
我手动添加环境变量后可以推送了

**Comment by KudouRan** [comment]
环境变量能且只能通过配置 secret 的 `TENCENT_SERVERLESS_YML` 。

secret 配置的东西只能被 github action 读取。你的程序最终是运行到腾讯云的，而不是在 github action。

环境变量是必须在 `serverless.yml` （`TENCENT_SERVERLESS_YML`）或者腾讯云的控制台配置的。

```yaml
 environment:
    variables: # 根据自己的需要修改
      Ray_BiliBiliCookies__1: 123 # cookie，必填
      Ray_Security__RandomSleepMaxMin: 20
      Ray_Security__IntervalSecondsBetweenRequestApi: 20
```

详见文档： https://github.com/RayWangQvQ/BiliBiliToolPro/tree/main/tencentScf#31-%E6%96%B9%E5%BC%8F%E4%B8%80actions%E8%87%AA%E5%8A%A8%E9%83%A8%E7%BD%B2%E6%8E%A8%E8%8D%90
