### ISSUE TITLE
【建议】<请在标题中清晰地概述你的建议>

### ISSUE THREAD

**Issue by lichlaughing** [RayWangQvQ/BiliBiliToolPro#946]
### 确认

✅  是的，我已搜索并确认，没有其他相同的议题

### 建议内容

能否在 web 端增加一个任务，来测试消息通知。
另外，我使用 docker-compose 部署，配置了 Bark Api 自定义通知，但是始终不生效，不知道为何。我在 docker-compose.yml 中这样配置：
```yaml
services:
  bili_tool_web:
    image: ghcr.io/raywangqvq/bili_tool_web
    container_name: bili_tool_web
    restart: unless-stopped
    tty: true
    volumes:
      - ./Logs:/app/Logs
      - ./config:/app/config
    ports:
      - "22330:8080"
    environment:
      TZ: "Asia/Shanghai"
      DailyTaskConfig__Cron: "0 0 15 * * ?"
      Ray_Serilog__WriteTo__8__Args__api: "https://bark.abcd.cn/push"
      Ray_Serilog__WriteTo__8__Args__bodyJsonTemplate: '{ "device_key": "abcd","title": "BiliBili","body":"#msg#"}'
```
